### ISSUE TITLE
Blueprint specific support

### ISSUE THREAD

**Issue by Zaffer** [wntrblm/flask-talisman#19]
How or can we do route specific talisman features on a blueprint of routes instead of just one route at a time or on the whole app?

ie: can you put a @talisman decorator on a blueprint?

**Comment by Jonakemon** [comment]
Hey @Zaffer, you can override the Talisman settings per route with a decorator like this:

```python
from flask import Flask
from flask_talisman import Talisman

app = Flask(__name__)
talisman = Talisman(app, force_https=False)
unsafe_script = "<script>alert('danger!');</script>"


@app.route("/")
def protected():
    return unsafe_script  # check browser console for CSP error


@app.route("/unprotected")
@talisman(content_security_policy=[])
def unprotected():
    return unsafe_script
```

It'll be quite a bit more difficult to override the app-wide Talisman config for an entire Blueprint. It will be difficult because Talisman uses the Flask [@after_request](https://flask.palletsprojects.com/en/2.0.x/api/#flask.Flask.after_request) decorator  [internally to set the response headers](https://github.com/wntrblm/flask-talisman/blob/a7a36f58c0b2f75ed6c0b5d1dc56fb97dae3414a/flask_talisman/talisman.py#L214).

These after_request functions are ran in [reversed order](https://github.com/pallets/flask/blob/3897a518014931a82c77a353e1e9c2248529b856/src/flask/app.py#L1877): first blueprint specific after_requests are ran and  then app-wide after_requests are ran (i.e. those defined by extensions like Talisman). This means that defining a response header in a Blueprint specific request will be overriden by the Talisman after_request function. 

There are three things you could do:
1. Preferred: Using route-based decorators
2. Tedious: Defining Talisman not on an app level, but on a Blueprint specific level
3. Dangerous: Modify the list of after_request functions on runtime, popping the Talisman after_request function in your blueprint specific after_request (not preferable, possibly buggy, I have not found any example or anyone mentioning that they do this).
